#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtgraphicaleffects
Version  : 5.14.0
Release  : 21
URL      : https://download.qt.io/official_releases/qt/5.14/5.14.0/submodules/qtgraphicaleffects-everywhere-src-5.14.0.tar.xz
Source0  : https://download.qt.io/official_releases/qt/5.14/5.14.0/submodules/qtgraphicaleffects-everywhere-src-5.14.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qtgraphicaleffects-lib = %{version}-%{release}
Requires: qtgraphicaleffects-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Test)

%description
No detailed description available

%package lib
Summary: lib components for the qtgraphicaleffects package.
Group: Libraries
Requires: qtgraphicaleffects-license = %{version}-%{release}

%description lib
lib components for the qtgraphicaleffects package.


%package license
Summary: license components for the qtgraphicaleffects package.
Group: Default

%description license
license components for the qtgraphicaleffects package.


%prep
%setup -q -n qtgraphicaleffects-everywhere-src-5.14.0
cd %{_builddir}/qtgraphicaleffects-everywhere-src-5.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1576218661
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtgraphicaleffects
cp %{_builddir}/qtgraphicaleffects-everywhere-src-5.14.0/LICENSE.FDL %{buildroot}/usr/share/package-licenses/qtgraphicaleffects/61907422fefcd2313a9b570c31d203a6dbebd333
cp %{_builddir}/qtgraphicaleffects-everywhere-src-5.14.0/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qtgraphicaleffects/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/qtgraphicaleffects-everywhere-src-5.14.0/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/qtgraphicaleffects/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/qtgraphicaleffects-everywhere-src-5.14.0/LICENSE.GPL3-EXCEPT %{buildroot}/usr/share/package-licenses/qtgraphicaleffects/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
cp %{_builddir}/qtgraphicaleffects-everywhere-src-5.14.0/LICENSE.LGPL3 %{buildroot}/usr/share/package-licenses/qtgraphicaleffects/f45ee1c765646813b442ca58de72e20a64a7ddba
%make_install

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/qml/QtGraphicalEffects/Blend.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/BrightnessContrast.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ColorOverlay.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Colorize.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ConicalGradient.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Desaturate.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/DirectionalBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Displace.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/DropShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/FastBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/GammaAdjust.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/GaussianBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/Glow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/HueSaturation.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/InnerShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/LevelAdjust.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/LinearGradient.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/MaskedBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/OpacityMask.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RadialBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RadialGradient.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RectangularGlow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/RecursiveBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ThresholdMask.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/ZoomBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
/usr/lib64/qt5/qml/QtGraphicalEffects/plugins.qmltypes
/usr/lib64/qt5/qml/QtGraphicalEffects/private/DropShadowBase.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/DropShadowBase.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastGlow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastGlow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastInnerShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastInnerShadow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastMaskedBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/FastMaskedBlur.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianDirectionalBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianDirectionalBlur.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianGlow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianGlow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianInnerShadow.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianInnerShadow.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianMaskedBlur.qml
/usr/lib64/qt5/qml/QtGraphicalEffects/private/GaussianMaskedBlur.qmlc
/usr/lib64/qt5/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
/usr/lib64/qt5/qml/QtGraphicalEffects/private/qmldir
/usr/lib64/qt5/qml/QtGraphicalEffects/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtgraphicaleffects/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qtgraphicaleffects/61907422fefcd2313a9b570c31d203a6dbebd333
/usr/share/package-licenses/qtgraphicaleffects/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qtgraphicaleffects/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
/usr/share/package-licenses/qtgraphicaleffects/f45ee1c765646813b442ca58de72e20a64a7ddba
